"""Wurstbrot GE Calculator 2.0 core engine."""

__version__ = "0.9.0-beta"

from .database import VehicleDatabase
from .graph_adapter import GraphDatabaseAdapter
from .graph_cost import (
    ALLOWED_SL_DISCOUNTS,
    CostStatus,
    GraphCostEngine,
    GraphCostResult,
    GraphVehicleCostLine,
)
from .graph_cost_analysis import (
    CostShadowCase,
    CostShadowComparisonDetail,
    CostShadowComparisonSummary,
    CostSpecialCaseSummary,
    build_cost_scenarios,
    build_cost_special_case_matrix,
    build_full_cost_shadow_cases,
    render_cost_special_case_markdown,
    run_cost_shadow_comparison,
)
from .dual_engine import (
    COMPARABLE_FIELDS,
    DUAL_FINGERPRINT_VERSION,
    EXCLUDED_FIELDS,
    ComparisonDifference,
    ComparisonStatus,
    DualEngineResult,
    DualEngineRunner,
    LegacyExecutionResult,
)
from .graph_analysis import (
    MirrorEvaluationSummary,
    build_special_case_matrix,
    render_special_case_matrix_markdown,
    run_mirror_evaluation,
)
from .graph_evaluation import (
    EvaluationStatus,
    GraphEvaluationReport,
    GraphRuleEvaluator,
    RuleEvaluation,
    UnlockClassification,
)
from .graph_pipeline import (
    DATAMINE_VALIDATION_RULE_IDS,
    FINGERPRINT_VERSION,
    INPUT_VALIDATION_RULE_IDS,
    GraphCalculationPipeline,
    GraphPipelineResult,
    PipelineInputFinding,
    PipelineStatus,
    PipelineStatusContract,
    ValidationCategory,
    ValidationSeverity,
)
from .graph_semantics import EDGE_SEMANTICS, EdgeSemantics, semantics_for
from .graph_resolution import (
    FolderRequirementResolution,
    GraphPrerequisiteResolver,
    LegacyRankCompatibilityStrategy,
    PrerequisiteResolution,
    RankCompatibilitySelection,
    RankRequirementResolution,
    ResolutionStatus,
    UnlockRequirementResolution,
)
from .graph_resolution_analysis import (
    ResolutionSpecialCaseSummary,
    ShadowCase,
    ShadowComparisonDetail,
    ShadowComparisonSummary,
    build_full_shadow_cases,
    build_player_progress_scenarios,
    build_resolution_special_case_matrix,
    render_resolution_special_case_markdown,
    run_shadow_comparison,
)
from .graph_shadow import (
    COUNTING_LEVELS,
    KNOWN_CONTRACT_DIFFERENCES,
    KNOWN_LIMITS,
    OPTION_COVERAGE_LABELS,
    DualEngineCase,
    FullShadowSummary,
    build_full_pipeline_cases,
    build_input_validation_cases,
    build_options_compatibility_cases,
    build_special_cases,
    render_shadow_text,
    run_full_pipeline_shadow,
    write_shadow_reports,
)
from .models import PlayerProgress, SolveOptions, SolveResult, VehicleProgress
from .research_graph import (
    EdgeType,
    DiagnosticCategory,
    GraphDiagnostics,
    GraphEdge,
    GraphNode,
    NodeType,
    ResearchGraph,
    ResearchGraphBuilder,
)
from .solver import ResearchSolver

__all__ = [
    "VehicleDatabase",
    "GraphDatabaseAdapter",
    "CostStatus",
    "ALLOWED_SL_DISCOUNTS",
    "GraphVehicleCostLine",
    "GraphCostResult",
    "GraphCostEngine",
    "PipelineStatus",
    "ValidationCategory",
    "ValidationSeverity",
    "PipelineInputFinding",
    "PipelineStatusContract",
    "GraphPipelineResult",
    "GraphCalculationPipeline",
    "FINGERPRINT_VERSION",
    "INPUT_VALIDATION_RULE_IDS",
    "DATAMINE_VALIDATION_RULE_IDS",
    "ComparisonStatus",
    "ComparisonDifference",
    "LegacyExecutionResult",
    "DualEngineResult",
    "DualEngineRunner",
    "DUAL_FINGERPRINT_VERSION",
    "COMPARABLE_FIELDS",
    "EXCLUDED_FIELDS",
    "DualEngineCase",
    "FullShadowSummary",
    "COUNTING_LEVELS",
    "OPTION_COVERAGE_LABELS",
    "KNOWN_CONTRACT_DIFFERENCES",
    "KNOWN_LIMITS",
    "build_full_pipeline_cases",
    "build_options_compatibility_cases",
    "build_input_validation_cases",
    "build_special_cases",
    "run_full_pipeline_shadow",
    "render_shadow_text",
    "write_shadow_reports",
    "CostShadowCase",
    "CostShadowComparisonDetail",
    "CostShadowComparisonSummary",
    "CostSpecialCaseSummary",
    "run_cost_shadow_comparison",
    "build_full_cost_shadow_cases",
    "build_cost_scenarios",
    "build_cost_special_case_matrix",
    "render_cost_special_case_markdown",
    "MirrorEvaluationSummary",
    "run_mirror_evaluation",
    "build_special_case_matrix",
    "render_special_case_matrix_markdown",
    "NodeType",
    "EdgeType",
    "DiagnosticCategory",
    "GraphNode",
    "GraphEdge",
    "GraphDiagnostics",
    "ResearchGraph",
    "ResearchGraphBuilder",
    "EdgeSemantics",
    "EDGE_SEMANTICS",
    "semantics_for",
    "EvaluationStatus",
    "UnlockClassification",
    "RuleEvaluation",
    "GraphEvaluationReport",
    "GraphRuleEvaluator",
    "ResolutionStatus",
    "RankCompatibilitySelection",
    "RankRequirementResolution",
    "FolderRequirementResolution",
    "UnlockRequirementResolution",
    "PrerequisiteResolution",
    "GraphPrerequisiteResolver",
    "LegacyRankCompatibilityStrategy",
    "ShadowCase",
    "ShadowComparisonDetail",
    "ShadowComparisonSummary",
    "ResolutionSpecialCaseSummary",
    "run_shadow_comparison",
    "build_full_shadow_cases",
    "build_player_progress_scenarios",
    "build_resolution_special_case_matrix",
    "render_resolution_special_case_markdown",
    "VehicleProgress",
    "PlayerProgress",
    "SolveOptions",
    "SolveResult",
    "ResearchSolver",
    "__version__",
]
